productpage:
  image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2

details:
  image: docker.io/istio/examples-bookinfo-details-v1:1.16.2

reviews:
  v1:
    image: docker.io/istio/examples-bookinfo-reviews-v1:1.16.2
  v2:
    image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
  v3:
    image: docker.io/istio/examples-bookinfo-reviews-v3:1.16.2

ratings:
  image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.2